### ISSUE TITLE
docker启动报错，一直循环重启

### ISSUE THREAD

**Issue by qingqidai** [cym1102/nginxWebUI#100]
日志：
ERROR 2023-08-15 14:28:58.676 [-main][*][com.cym.NginxWebUI]:
AopContext start failed
java.lang.IllegalStateException: AopContext start failed
	at org.noear.solon.core.AopContext.start(AopContext.java:766)
	at org.noear.solon.SolonApp.run(SolonApp.java:212)
	at org.noear.solon.SolonApp.start(SolonApp.java:97)
	at org.noear.solon.Solon.start(Solon.java:154)
	at org.noear.solon.Solon.start(Solon.java:117)
	at com.cym.NginxWebUI.main(NginxWebUI.java:39)
Caused by: cn.hutool.core.io.IORuntimeException: IOException: Cannot run program "chmod": error=1, Operation not permitted
	at cn.hutool.core.util.RuntimeUtil.exec(RuntimeUtil.java:86)
	at com.cym.config.InitConfig.start(InitConfig.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.noear.solon.core.BeanWrap.initInvokeDo(BeanWrap.java:245)
	at org.noear.solon.core.BeanWrap.lambda$init$0(BeanWrap.java:237)
	at org.noear.solon.core.AopContext.start(AopContext.java:758)
	... 5 common frames omitted
Caused by: java.io.IOException: Cannot run program "chmod": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at cn.hutool.core.util.RuntimeUtil.exec(RuntimeUtil.java:84)
	... 13 common frames omitted
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 common frames omitted
INFO  2023-08-15 14:28:58.683 [-main][*][o.noear.solon.Solon]:
Server:main: undertow: Has Stopped (undertow 2.2.24/2.3.8)

**Comment by cym1102** [comment]
确实不知道咋回事,为什么没有chmod命令

**Comment by whhya** [comment]
请问这个问题最终如何解决呢?

**Comment by cym1102** [comment]
不清楚你的运行环境, 这个只有你自己找找原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月15日(星期五) 上午10:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] docker启动报错，一直循环重启 (Issue #100)





 
请问这个问题最终如何解决呢?

**Comment by whhya** [comment]
阿里云的服务器,Alibaba Cloud Linux  2.1903 LTS 64位
之前都好好的,昨天阿里云服务器通知要停服更新,然后重启之后就再也起不来了,莫名其妙服了







huihuang&nbsp;Wu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月15日(星期五) 上午10:32
***@***.***&gt;;
抄送:&nbsp;"huihuang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cym1102/nginxWebUI] docker启动报错，一直循环重启 (Issue #100)





 不清楚你的运行环境, 这个只有你自己找找原因 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年9月15日(星期五) 上午10:31 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [cym1102/nginxWebUI] docker启动报错，一直循环重启 (Issue #100) 
 
 
 
 
 

 请问这个问题最终如何解决呢?
