### ISSUE TITLE
linux中无法执行chmod代码

### ISSUE THREAD

**Issue by mintonzhang** [cym1102/nginxWebUI#109]
此代码会报错
https://github.com/cym1102/nginxWebUI/blob/bfbf2200df4b338c89a15267a46dc840f4d8aaea/src/main/java/com/cym/config/InitConfig.java#L130

当前服务器配置

Linux iZt4nfguoekmlylf2g20uuZ 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

提示错误
```
Exception in thread "main" java.lang.IllegalStateException: SolonApp start failed
        at org.noear.solon.Solon.start(Solon.java:164)
        at org.noear.solon.Solon.start(Solon.java:117)
        at com.cym.NginxWebUI.main(NginxWebUI.java:39)
Caused by: java.lang.IllegalStateException: AopContext start failed
        at org.noear.solon.core.AopContext.start(AopContext.java:756)
        at org.noear.solon.SolonApp.run(SolonApp.java:212)
        at org.noear.solon.SolonApp.start(SolonApp.java:97)
        at org.noear.solon.Solon.start(Solon.java:154)
        ... 2 more
Caused by: cn.hutool.core.io.IORuntimeException: IOException: Cannot run program "chmod": error=1, Operation not permitted
        at cn.hutool.core.util.RuntimeUtil.exec(RuntimeUtil.java:86)
        at com.cym.config.InitConfig.start(InitConfig.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.noear.solon.core.BeanWrap.initInvokeDo(BeanWrap.java:245)
        at org.noear.solon.core.BeanWrap.lambda$init$0(BeanWrap.java:237)
        at org.noear.solon.core.AopContext.start(AopContext.java:748)
        ... 5 more
Caused by: java.io.IOException: Cannot run program "chmod": error=1, Operation not permitted
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at cn.hutool.core.util.RuntimeUtil.exec(RuntimeUtil.java:84)
        ... 13 more
Caused by: java.io.IOException: error=1, Operation not permitted
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 14 more
```
docker-compose 文件
```
version: "3.2"
services:
  nginxWebUi:
    image: cym1102/nginxwebui:3.6.0
    volumes:
      - /opt/nginxWebUI:/home/nginxWebUI
    environment:
      - "BOOT_OPTIONS=--server.port=8080"
    privileged: true
    network_mode: "host"
    container_name: nginxWebUi
```

容器中是存在该命令的，
```
[root@iZt4nfguoekmlylf2g20uuZ docker-compose]# docker ps -a|grep nginxweb
f09c3d3bdb4c        cym1102/nginxwebui:3.6.0           "tini entrypoint.sh"     43 minutes ago      Exited (1) 2 minutes ago                            nginxWebUi
[root@iZt4nfguoekmlylf2g20uuZ docker-compose]# docker start f09c3d3bdb4c && docker exec -it f09c3d3bdb4c chmod
f09c3d3bdb4c
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
```

我重新在阿里云买一台新加坡的轻量服务器，镜像配置如下，也会出现该问题
<img width="1402" alt="image" src="https://github.com/cym1102/nginxWebUI/assets/45935465/7bdaa39f-907d-4890-a5c6-31caf4b0a18c">

**Comment by cym1102** [comment]
这个确实没法帮你定位问题
