### ISSUE TITLE
启用配置页面报错“联系开发者”

### ISSUE THREAD

**Issue by SurefireRyan** [cym1102/nginxWebUI#164]
![ae71acee21682ae8ab47cfe5f8d8e969](https://github.com/user-attachments/assets/eca19dc1-b8a7-4763-a843-05a7e7524b23)

**Comment by SurefireRyan** [comment]
环境为群晖 docker部署

**Comment by SurefireRyan** [comment]
ERROR 2024-09-02 18:01:12.814 [-XNIO-1 task-1][*][c.c.s.ConfService]: 
null
java.lang.NullPointerException: null
	at com.cym.service.ConfService.buildConf(ConfService.java:97)
	at com.cym.controller.adminPage.ConfController.loadOrg(ConfController.java:419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.noear.solon.core.wrap.MethodWrap.invoke(MethodWrap.java:234)
	at org.noear.solon.core.wrap.MethodWrap.doIntercept(MethodWrap.java:226)
	at org.noear.solon.core.aspect.InterceptorEntity.doIntercept(InterceptorEntity.java:34)
	at org.noear.solon.core.aspect.Invocation.invoke(Invocation.java:78)
	at org.noear.solon.core.wrap.MethodWrap.invokeByAspect(MethodWrap.java:246)
	at org.noear.solon.core.handle.ActionExecuteHandlerDefault.executeHandle(ActionExecuteHandlerDefault.java:45)
	at org.noear.solon.core.handle.Action.executeDo(Action.java:324)
	at org.noear.solon.core.handle.Action.invoke0(Action.java:263)
	at org.noear.solon.core.handle.Action.invoke(Action.java:210)
	at org.noear.solon.core.handle.Action.handle(Action.java:191)
	at org.noear.solon.core.route.RouterHandler.handleMain(RouterHandler.java:32)
	at org.noear.solon.core.route.RouterHandler.handleDo(RouterHandler.java:63)
	at org.noear.solon.core.route.RouterHandler.doIntercept(RouterHandler.java:23)
	at org.noear.solon.core.route.RouterInterceptorLimiter.doIntercept(RouterInterceptorLimiter.java:47)
	at org.noear.solon.core.route.RouterInterceptorChainImpl.doIntercept(RouterInterceptorChainImpl.java:27)
	at org.noear.solon.core.ChainManager.doIntercept(ChainManager.java:96)
	at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:92)
	at org.noear.solon.core.handle.HandlerPipeline.handle(HandlerPipeline.java:41)
	at org.noear.solon.SolonApp.doFilter(SolonApp.java:448)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at com.cym.config.AppFilter.doFilter(AppFilter.java:110)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.logging.integration.XPluginImp.lambda$start$1(XPluginImp.java:54)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.core.ChainManager.doFilter(ChainManager.java:49)
	at org.noear.solon.SolonApp.tryHandle(SolonApp.java:400)
	at org.noear.solon.web.servlet.SolonServletHandler.service(SolonServletHandler.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.lang.Thread.run(Thread.java:750)
ERROR 2024-09-02 18:01:12.825 [-XNIO-1 task-1][*][com.cym.NginxWebUI]: 
null
java.lang.NullPointerException: null
	at com.cym.controller.adminPage.ConfController.loadOrg(ConfController.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.noear.solon.core.wrap.MethodWrap.invoke(MethodWrap.java:234)
	at org.noear.solon.core.wrap.MethodWrap.doIntercept(MethodWrap.java:226)
	at org.noear.solon.core.aspect.InterceptorEntity.doIntercept(InterceptorEntity.java:34)
	at org.noear.solon.core.aspect.Invocation.invoke(Invocation.java:78)
	at org.noear.solon.core.wrap.MethodWrap.invokeByAspect(MethodWrap.java:246)
	at org.noear.solon.core.handle.ActionExecuteHandlerDefault.executeHandle(ActionExecuteHandlerDefault.java:45)
	at org.noear.solon.core.handle.Action.executeDo(Action.java:324)
	at org.noear.solon.core.handle.Action.invoke0(Action.java:263)
	at org.noear.solon.core.handle.Action.invoke(Action.java:210)
	at org.noear.solon.core.handle.Action.handle(Action.java:191)
	at org.noear.solon.core.route.RouterHandler.handleMain(RouterHandler.java:32)
	at org.noear.solon.core.route.RouterHandler.handleDo(RouterHandler.java:63)
	at org.noear.solon.core.route.RouterHandler.doIntercept(RouterHandler.java:23)
	at org.noear.solon.core.route.RouterInterceptorLimiter.doIntercept(RouterInterceptorLimiter.java:47)
	at org.noear.solon.core.route.RouterInterceptorChainImpl.doIntercept(RouterInterceptorChainImpl.java:27)
	at org.noear.solon.core.ChainManager.doIntercept(ChainManager.java:96)
	at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:92)
	at org.noear.solon.core.handle.HandlerPipeline.handle(HandlerPipeline.java:41)
	at org.noear.solon.SolonApp.doFilter(SolonApp.java:448)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at com.cym.config.AppFilter.doFilter(AppFilter.java:110)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.logging.integration.XPluginImp.lambda$start$1(XPluginImp.java:54)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.core.ChainManager.doFilter(ChainManager.java:49)
	at org.noear.solon.SolonApp.tryHandle(SolonApp.java:400)
	at org.noear.solon.web.servlet.SolonServletHandler.service(SolonServletHandler.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.lang.Thread.run(Thread.java:750)
ERROR 2024-09-02 18:01:12.825 [-XNIO-1 task-5][*][c.c.s.ConfService]: 
null
java.lang.NullPointerException: null
	at com.cym.service.ConfService.buildConf(ConfService.java:97)
	at com.cym.controller.adminPage.ConfController.loadConf(ConfController.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.noear.solon.core.wrap.MethodWrap.invoke(MethodWrap.java:234)
	at org.noear.solon.core.wrap.MethodWrap.doIntercept(MethodWrap.java:226)
	at org.noear.solon.core.aspect.InterceptorEntity.doIntercept(InterceptorEntity.java:34)
	at org.noear.solon.core.aspect.Invocation.invoke(Invocation.java:78)
	at org.noear.solon.core.wrap.MethodWrap.invokeByAspect(MethodWrap.java:246)
	at org.noear.solon.core.handle.ActionExecuteHandlerDefault.executeHandle(ActionExecuteHandlerDefault.java:45)
	at org.noear.solon.core.handle.Action.executeDo(Action.java:324)
	at org.noear.solon.core.handle.Action.invoke0(Action.java:263)
	at org.noear.solon.core.handle.Action.invoke(Action.java:210)
	at org.noear.solon.core.handle.Action.handle(Action.java:191)
	at org.noear.solon.core.route.RouterHandler.handleMain(RouterHandler.java:32)
	at org.noear.solon.core.route.RouterHandler.handleDo(RouterHandler.java:63)
	at org.noear.solon.core.route.RouterHandler.doIntercept(RouterHandler.java:23)
	at org.noear.solon.core.route.RouterInterceptorLimiter.doIntercept(RouterInterceptorLimiter.java:47)
	at org.noear.solon.core.route.RouterInterceptorChainImpl.doIntercept(RouterInterceptorChainImpl.java:27)
	at org.noear.solon.core.ChainManager.doIntercept(ChainManager.java:96)
	at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:92)
	at org.noear.solon.core.handle.HandlerPipeline.handle(HandlerPipeline.java:41)
	at org.noear.solon.SolonApp.doFilter(SolonApp.java:448)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at com.cym.config.AppFilter.doFilter(AppFilter.java:110)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.logging.integration.XPluginImp.lambda$start$1(XPluginImp.java:54)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.core.ChainManager.doFilter(ChainManager.java:49)
	at org.noear.solon.SolonApp.tryHandle(SolonApp.java:400)
	at org.noear.solon.web.servlet.SolonServletHandler.service(SolonServletHandler.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.lang.Thread.run(Thread.java:750)
报错日志

**Comment by SurefireRyan** [comment]
基本参数的问题，全部删了即可解决
