### ISSUE TITLE
使用ibm-jdk8或者21获取验证码报错

### ISSUE THREAD

**Issue by stylesmile** [cym1102/nginxWebUI#168]
tail -f stdout.log 
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.lang.Thread.run(Thread.java:826)
ERROR 2024-09-17 05:51:13.337 [-XNIO-1 task-1][*][com.cym.NginxWebUI]: 
null
java.lang.NullPointerException: null
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:441)
	at java.security.AccessController.doPrivileged(AccessController.java:691)
	at sun.font.SunFontManager.<init>(SunFontManager.java:386)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:2108)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(AccessController.java:691)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:860)
	at com.wf.captcha.SpecCaptcha.graphicsImage(SpecCaptcha.java:76)
	at com.wf.captcha.SpecCaptcha.out(SpecCaptcha.java:45)
	at com.cym.controller.adminPage.LoginController.getCode(LoginController.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.noear.solon.core.wrap.MethodWrap.invoke(MethodWrap.java:234)
	at org.noear.solon.core.wrap.MethodWrap.doIntercept(MethodWrap.java:226)
	at org.noear.solon.core.aspect.InterceptorEntity.doIntercept(InterceptorEntity.java:34)
	at org.noear.solon.core.aspect.Invocation.invoke(Invocation.java:78)
	at org.noear.solon.core.wrap.MethodWrap.invokeByAspect(MethodWrap.java:246)
	at org.noear.solon.core.handle.ActionExecuteHandlerDefault.executeHandle(ActionExecuteHandlerDefault.java:45)
	at org.noear.solon.core.handle.Action.executeDo(Action.java:324)
	at org.noear.solon.core.handle.Action.invoke0(Action.java:263)
	at org.noear.solon.core.handle.Action.invoke(Action.java:210)
	at org.noear.solon.core.handle.Action.handle(Action.java:191)
	at org.noear.solon.core.route.RouterHandler.handleMain(RouterHandler.java:32)
	at org.noear.solon.core.route.RouterHandler.handleDo(RouterHandler.java:63)
	at org.noear.solon.core.route.RouterHandler.doIntercept(RouterHandler.java:23)
	at org.noear.solon.core.route.RouterInterceptorLimiter.doIntercept(RouterInterceptorLimiter.java:47)
	at org.noear.solon.core.route.RouterInterceptorChainImpl.doIntercept(RouterInterceptorChainImpl.java:27)
	at org.noear.solon.core.ChainManager.doIntercept(ChainManager.java:96)
	at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:92)
	at org.noear.solon.core.handle.HandlerPipeline.handle(HandlerPipeline.java:41)
	at org.noear.solon.SolonApp.doFilter(SolonApp.java:448)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at com.cym.config.AppFilter.doFilter(AppFilter.java:110)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.logging.integration.XPluginImp.lambda$start$1(XPluginImp.java:54)
	at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
	at org.noear.solon.core.ChainManager.doFilter(ChainManager.java:49)
	at org.noear.solon.SolonApp.tryHandle(SolonApp.java:400)
	at org.noear.solon.web.servlet.SolonServletHandler.service(SolonServletHandler.java:31)

**Comment by cym1102** [comment]
系统没有装字库 https://blog.csdn.net/crystonesc/article/details/86305466 

yum install fontconfig fc-cache --force


***@***.***
 
发件人： Stylesmile
发送时间： 2024-09-17 13:53
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 使用ibm-jdk8或者21获取验证码报错 (Issue #168)
tail -f stdout.log
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
at java.lang.Thread.run(Thread.java:826)
ERROR 2024-09-17 05:51:13.337 [-XNIO-1 task-1][*][com.cym.NginxWebUI]:
null
java.lang.NullPointerException: null
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
at sun.font.SunFontManager$2.run(SunFontManager.java:441)
at java.security.AccessController.doPrivileged(AccessController.java:691)
at sun.font.SunFontManager.(SunFontManager.java:386)
at sun.awt.FcFontManager.(FcFontManager.java:35)
at sun.awt.X11FontManager.(X11FontManager.java:57)
at java.lang.J9VMInternals.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:2108)
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
at java.security.AccessController.doPrivileged(AccessController.java:691)
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:860)
at com.wf.captcha.SpecCaptcha.graphicsImage(SpecCaptcha.java:76)
at com.wf.captcha.SpecCaptcha.out(SpecCaptcha.java:45)
at com.cym.controller.adminPage.LoginController.getCode(LoginController.java:305)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.noear.solon.core.wrap.MethodWrap.invoke(MethodWrap.java:234)
at org.noear.solon.core.wrap.MethodWrap.doIntercept(MethodWrap.java:226)
at org.noear.solon.core.aspect.InterceptorEntity.doIntercept(InterceptorEntity.java:34)
at org.noear.solon.core.aspect.Invocation.invoke(Invocation.java:78)
at org.noear.solon.core.wrap.MethodWrap.invokeByAspect(MethodWrap.java:246)
at org.noear.solon.core.handle.ActionExecuteHandlerDefault.executeHandle(ActionExecuteHandlerDefault.java:45)
at org.noear.solon.core.handle.Action.executeDo(Action.java:324)
at org.noear.solon.core.handle.Action.invoke0(Action.java:263)
at org.noear.solon.core.handle.Action.invoke(Action.java:210)
at org.noear.solon.core.handle.Action.handle(Action.java:191)
at org.noear.solon.core.route.RouterHandler.handleMain(RouterHandler.java:32)
at org.noear.solon.core.route.RouterHandler.handleDo(RouterHandler.java:63)
at org.noear.solon.core.route.RouterHandler.doIntercept(RouterHandler.java:23)
at org.noear.solon.core.route.RouterInterceptorLimiter.doIntercept(RouterInterceptorLimiter.java:47)
at org.noear.solon.core.route.RouterInterceptorChainImpl.doIntercept(RouterInterceptorChainImpl.java:27)
at org.noear.solon.core.ChainManager.doIntercept(ChainManager.java:96)
at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:92)
at org.noear.solon.core.handle.HandlerPipeline.handle(HandlerPipeline.java:41)
at org.noear.solon.SolonApp.doFilter(SolonApp.java:448)
at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
at com.cym.config.AppFilter.doFilter(AppFilter.java:110)
at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
at org.noear.solon.logging.integration.XPluginImp.lambda$start$1(XPluginImp.java:54)
at org.noear.solon.core.handle.FilterChainImpl.doFilter(FilterChainImpl.java:24)
at org.noear.solon.core.ChainManager.doFilter(ChainManager.java:49)
at org.noear.solon.SolonApp.tryHandle(SolonApp.java:400)
at org.noear.solon.web.servlet.SolonServletHandler.service(SolonServletHandler.java:31)
